### PR TITLE
Add CSS to desktop

### PR DESCRIPTION
**Pull request by dietbrand**
This PR sets the basis for the design. I used emoji for the buttons and moved the add button (the massive plus sign) to the bottom right.

This PR effectively deprecates the design. I'm not sure if we should redo the design file to reflect this.

You can uncomment the divs in the HTML to see how the overflow works once we start generating the HTML with JavaScript. You will see that we have a decent amount of space on the right so we may be able to use that to move the menu to there, perhaps when we start scrolling?

### CODE REVIEW

**Review by tluyckx — COMMENTED** [review]
Code looks fine to me! 👌

The only thing bothering me is that the emojis will probably look different depending on the user's default font or system.

How it looks now:
image

I don't know if the difference in style is intentional? The first one is an emoji, the other ones seem to be ASCII codes, like the [gear](https://www.compart.com/en/unicode/U+2699).

This might also be the reason they take up different amounts of space.

I suggest using an icon library for this, like [Fontawesome](https://fontawesome.com/) or [Google Fonts](https://fonts.google.com/icons).

**Comment by tluyckx** [comment]
I don't think it's necessary to modify the design file, as this will likely change a few more times. It's good to keep it as a reference, but I think we'll see what works or not during development/testing.

The menu could indeed switch to the right side when scrolling.

**Comment by camelopardalus** [comment]
I don't think it's necessary to modify the design file, as this will likely change a few more times. It's good to keep it as a reference, but I think we'll see what works or not during development/testing.

The menu could indeed switch to the right side when scrolling.

**Comment by dietbrand** [comment]
Emoji styles are very different across apps and vendors. I'll update the branch to use icons in the menu.

**Comment by dietbrand** [comment]
I added Ionicons to the project: https://ionic.io/ionicons

**Review by tluyckx — APPROVED** [review]

**Pull request merged**
